# Generated by Django 2.2 on 2020-02-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'industry_list',
            },
        ),
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=9, verbose_name='ST代码')),
                ('symbol', models.CharField(max_length=9, verbose_name='股票代码')),
                ('name', models.CharField(max_length=50, verbose_name='股票名称')),
                ('area', models.CharField(max_length=30, verbose_name='所在地域')),
                ('industry', models.CharField(max_length=30, verbose_name='所属行业')),
                ('fullname', models.CharField(max_length=50, verbose_name='股票全称')),
                ('enname', models.CharField(max_length=300, verbose_name='英文全称')),
                ('market', models.CharField(max_length=30, verbose_name='市场类型')),
                ('exchange', models.CharField(max_length=10, verbose_name='交易所代码')),
                ('curr_type', models.CharField(max_length=10, verbose_name='交易货币')),
                ('list_status', models.CharField(max_length=10, verbose_name='上市状态')),
                ('list_date', models.CharField(max_length=8, verbose_name='上市日期')),
                ('delist_date', models.CharField(max_length=8, verbose_name='退市日期')),
                ('is_hs', models.CharField(max_length=10, verbose_name='是否沪深港通标的')),
            ],
            options={
                'db_table': 'stock_list',
            },
        ),
    ]
