# Generated by Django 2.2 on 2020-02-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklist',
            name='code',
        ),
        migrations.AddField(
            model_name='stocklist',
            name='ts_code',
            field=models.CharField(default='', max_length=9, verbose_name='TS代码'),
            preserve_default=False,
        ),
    ]
