# Generated by Django 2.2 on 2020-02-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_indexlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexlist',
            name='list_date',
            field=models.CharField(max_length=8, null=True, verbose_name='发布日期'),
        ),
    ]
