# Generated by Django 2.2 on 2020-02-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20200229_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexlist',
            name='base_date',
            field=models.CharField(max_length=8, null=True, verbose_name='基期'),
        ),
    ]
