# Generated by Django 2.2 on 2020-03-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20200229_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repurchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts_code', models.CharField(max_length=9, verbose_name='TS代码')),
                ('ann_date', models.CharField(max_length=8, verbose_name='公告日期')),
                ('end_date', models.CharField(max_length=8, verbose_name='截止日期')),
                ('proc', models.CharField(max_length=50, verbose_name='进度')),
                ('exp_date', models.CharField(max_length=8, verbose_name='过期日期')),
                ('vol', models.FloatField(verbose_name='回购数量')),
                ('amount', models.FloatField(verbose_name='回购金额')),
                ('high_limit', models.FloatField(verbose_name='回购最高价')),
                ('low_limit', models.FloatField(verbose_name='回购最低价')),
            ],
            options={
                'db_table': 'repurchase',
            },
        ),
    ]
