# Generated by Django 2.2 on 2020-03-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_repurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexlist',
            name='fun_one',
            field=models.CharField(default=0, max_length=1, verbose_name='过滤1'),
        ),
    ]
