# Generated by Django 2.2 on 2020-03-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20200307_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexlist',
            name='fun_thd',
            field=models.CharField(default=0, max_length=1, verbose_name='市值对比'),
        ),
    ]
