# Generated by Django 2.2 on 2020-03-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_indexlist_fun_thd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexlist',
            name='fun_one',
        ),
        migrations.RemoveField(
            model_name='indexlist',
            name='fun_thd',
        ),
        migrations.RemoveField(
            model_name='indexlist',
            name='fun_two',
        ),
        migrations.AddField(
            model_name='indexlist',
            name='others',
            field=models.CharField(default=0, max_length=1, verbose_name='选择参数'),
        ),
    ]
