# Generated by Django 2.2 on 2020-03-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20200315_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexlist',
            old_name='others',
            new_name='select_opt',
        ),
    ]
