# Generated by Django 2.2 on 2020-03-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20200315_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexlist',
            name='select_opt',
            field=models.CharField(default=0, max_length=30, verbose_name='选择参数'),
        ),
    ]
