# Generated by Django 2.2 on 2020-03-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_holdernumber_holdertrade_income_traderaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdertrade',
            name='begin_date',
            field=models.CharField(max_length=15, verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='holdertrade',
            name='close_date',
            field=models.CharField(max_length=15, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='holdertrade',
            name='holder_name',
            field=models.CharField(max_length=60, verbose_name='股东名称'),
        ),
        migrations.AlterField(
            model_name='holdertrade',
            name='holder_type',
            field=models.CharField(max_length=3, verbose_name='股东类型G高管P个人C公司'),
        ),
        migrations.AlterField(
            model_name='holdertrade',
            name='in_de',
            field=models.CharField(max_length=3, verbose_name='类型'),
        ),
    ]
