# Generated by Django 2.2 on 2020-03-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_auto_20200318_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Express',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts_code', models.CharField(max_length=15, verbose_name='TS股票代码')),
                ('ann_date', models.CharField(max_length=8, verbose_name='公告日期')),
                ('end_date', models.CharField(max_length=8, verbose_name='报告期')),
                ('revenue', models.FloatField(verbose_name='营业收入(元)')),
                ('operate_profit', models.FloatField(verbose_name='营业利润(元)')),
                ('total_profit', models.FloatField(verbose_name='利润总额(元)')),
                ('n_income', models.FloatField(verbose_name='净利润(元)')),
                ('total_assets', models.FloatField(verbose_name='总资产(元)')),
                ('total_hldr_eqy_exc_min_int', models.FloatField(verbose_name='股东权益合计(不含少数股东权益)(元)')),
                ('diluted_eps', models.FloatField(verbose_name='每股收益(摊薄)(元)')),
                ('diluted_roe', models.FloatField(verbose_name='净资产收益率(摊薄)(%)')),
                ('yoy_net_profit', models.FloatField(verbose_name='去年同期修正后净利润')),
                ('bps', models.FloatField(verbose_name='每股净资产')),
                ('yoy_sales', models.FloatField(verbose_name='同比增长率:营业收入')),
                ('yoy_op', models.FloatField(verbose_name='同比增长率:营业利润')),
                ('yoy_tp', models.FloatField(verbose_name='同比增长率:利润总额')),
                ('yoy_dedu_np', models.FloatField(verbose_name='同比增长率:归属母公司股东的净利润')),
                ('yoy_eps', models.FloatField(verbose_name='同比增长率:基本每股收益')),
                ('yoy_roe', models.FloatField(verbose_name='同比增减:加权平均净资产收益率')),
                ('growth_assets', models.FloatField(verbose_name='比年初增长率:总资产')),
                ('yoy_equity', models.FloatField(verbose_name='比年初增长率:归属母公司的股东权益')),
                ('growth_bps', models.FloatField(verbose_name='比年初增长率:归属于母公司股东的每股净资产')),
                ('or_last_year', models.FloatField(verbose_name='去年同期营业收入')),
                ('op_last_year', models.FloatField(verbose_name='去年同期营业利润')),
                ('tp_last_year', models.FloatField(verbose_name='去年同期利润总额')),
                ('np_last_year', models.FloatField(verbose_name='去年同期净利润')),
                ('eps_last_year', models.FloatField(verbose_name='去年同期每股收益')),
                ('open_net_assets', models.FloatField(verbose_name='期初净资产')),
                ('open_bps', models.FloatField(verbose_name='期初每股净资产')),
                ('perf_summary', models.CharField(max_length=600, verbose_name='业绩简要说明')),
                ('is_audit', models.FloatField(verbose_name='是否审计')),
                ('remark', models.CharField(max_length=100, verbose_name='备注')),
            ],
            options={
                'db_table': 'express',
            },
        ),
    ]
