# Generated by Django 2.2 on 2020-03-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_express'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='express',
            name='eps_last_year',
        ),
        migrations.RemoveField(
            model_name='express',
            name='growth_assets',
        ),
        migrations.RemoveField(
            model_name='express',
            name='growth_bps',
        ),
        migrations.RemoveField(
            model_name='express',
            name='is_audit',
        ),
        migrations.RemoveField(
            model_name='express',
            name='np_last_year',
        ),
        migrations.RemoveField(
            model_name='express',
            name='op_last_year',
        ),
        migrations.RemoveField(
            model_name='express',
            name='open_bps',
        ),
        migrations.RemoveField(
            model_name='express',
            name='open_net_assets',
        ),
        migrations.RemoveField(
            model_name='express',
            name='or_last_year',
        ),
        migrations.RemoveField(
            model_name='express',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='express',
            name='tp_last_year',
        ),
        migrations.RemoveField(
            model_name='express',
            name='yoy_dedu_np',
        ),
        migrations.RemoveField(
            model_name='express',
            name='yoy_eps',
        ),
        migrations.RemoveField(
            model_name='express',
            name='yoy_equity',
        ),
        migrations.RemoveField(
            model_name='express',
            name='yoy_op',
        ),
        migrations.RemoveField(
            model_name='express',
            name='yoy_roe',
        ),
        migrations.RemoveField(
            model_name='express',
            name='yoy_sales',
        ),
        migrations.RemoveField(
            model_name='express',
            name='yoy_tp',
        ),
    ]
