# Generated by Django 2.2 on 2020-03-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_auto_20200318_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts_code', models.CharField(max_length=9, verbose_name='基金代码')),
                ('name', models.CharField(max_length=50, verbose_name='简称')),
                ('management', models.CharField(max_length=500, verbose_name='管理人')),
                ('custodian', models.CharField(max_length=500, verbose_name='托管人')),
                ('fund_type', models.CharField(max_length=100, verbose_name='投资类型')),
                ('found_date', models.CharField(max_length=8, verbose_name='成立日期')),
                ('due_date', models.CharField(max_length=8, verbose_name='到期日期')),
                ('list_date', models.CharField(max_length=8, verbose_name='上市时间')),
                ('issue_date', models.CharField(max_length=8, verbose_name='发行日期')),
                ('delist_date', models.CharField(max_length=8, verbose_name='退市日期')),
                ('issue_amount', models.FloatField(verbose_name='发行份额(亿)')),
                ('m_fee', models.FloatField(verbose_name='管理费')),
                ('c_fee', models.FloatField(verbose_name='托管费')),
                ('duration_year', models.FloatField(verbose_name='存续期')),
                ('p_value', models.FloatField(verbose_name='面值')),
                ('min_amount', models.FloatField(verbose_name='起点金额(万元)')),
                ('exp_return', models.FloatField(verbose_name='预期收益率')),
                ('benchmark', models.CharField(max_length=50, verbose_name='业绩比较基准')),
                ('status', models.CharField(max_length=3, verbose_name='存续状态D摘牌 I发行 L已上市')),
                ('invest_type', models.CharField(max_length=300, verbose_name='投资风格')),
                ('ftype', models.CharField(max_length=50, verbose_name='基金类型')),
                ('trustee', models.CharField(max_length=50, verbose_name='受托人')),
                ('purc_startdate', models.CharField(max_length=8, verbose_name='日常申购起始日')),
                ('redm_startdate', models.CharField(max_length=8, verbose_name='日常赎回起始日')),
                ('market', models.CharField(max_length=3, verbose_name='E场内O场外')),
            ],
            options={
                'db_table': 'fund_list',
            },
        ),
        migrations.CreateModel(
            name='FundPortfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts_code', models.CharField(max_length=9, verbose_name='TS基金代码')),
                ('ann_date', models.CharField(max_length=8, verbose_name='公告日期')),
                ('end_date', models.CharField(max_length=8, verbose_name='截止日期')),
                ('symbol', models.CharField(max_length=9, verbose_name='股票代码')),
                ('mkv', models.FloatField(verbose_name='持有股票市值(元)')),
                ('amount', models.FloatField(verbose_name='持有股票数量（股）')),
                ('stk_mkv_ratio', models.FloatField(verbose_name='占股票市值比')),
                ('stk_float_ratio', models.FloatField(verbose_name='占流通股本比例')),
            ],
            options={
                'db_table': 'fund_portfolio',
            },
        ),
        migrations.CreateModel(
            name='Margin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trade_date', models.CharField(max_length=8, verbose_name='交易日期')),
                ('exchange_id', models.CharField(max_length=8, verbose_name='交易所代码（SSE上交所SZSE深交所）')),
                ('rzye', models.FloatField(verbose_name='融资余额(元)')),
                ('rzmre', models.FloatField(verbose_name='融资买入额(元)')),
                ('rzche', models.FloatField(verbose_name='融资偿还额(元)')),
                ('rqye', models.FloatField(verbose_name='融券余额(元)')),
                ('rqmcl', models.FloatField(verbose_name='融券卖出量(股,份,手)')),
                ('rzrqye', models.FloatField(verbose_name='融资融券余额(元)')),
                ('rqyl', models.FloatField(verbose_name='融券余量(股,份,手)')),
            ],
            options={
                'db_table': 'margin',
            },
        ),
        migrations.CreateModel(
            name='PledgeStat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts_code', models.CharField(max_length=9, verbose_name='TS代码')),
                ('end_date', models.CharField(max_length=8, verbose_name='截至日期')),
                ('pledge_count', models.FloatField(verbose_name='质押次数')),
                ('unrest_pledge', models.FloatField(verbose_name='无限售股质押数量（万）')),
                ('rest_pledge', models.FloatField(verbose_name='限售股份质押数量（万）')),
                ('total_share', models.FloatField(verbose_name='总股本')),
                ('pledge_ratio', models.FloatField(verbose_name='质押比例')),
            ],
            options={
                'db_table': 'pledge_stat',
            },
        ),
        migrations.CreateModel(
            name='ShareFloat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts_code', models.CharField(max_length=8, verbose_name='TS代码')),
                ('ann_date', models.CharField(max_length=8, verbose_name='公告日期')),
                ('float_date', models.CharField(max_length=8, verbose_name='解禁日期')),
                ('float_share', models.FloatField(verbose_name='流通股份')),
                ('float_ratio', models.FloatField(verbose_name='流通股份占总股本比率')),
                ('holder_name', models.CharField(max_length=50, verbose_name='股东名称')),
                ('share_type', models.CharField(max_length=50, verbose_name='股份类型')),
            ],
            options={
                'db_table': 'share_float',
            },
        ),
    ]
