# Generated by Django 2.2 on 2020-03-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_auto_20200321_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundlist',
            name='ts_code',
            field=models.CharField(max_length=15, verbose_name='基金代码'),
        ),
    ]
