# Generated by Django 2.2 on 2020-03-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_auto_20200321_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundportfolio',
            name='ann_date',
            field=models.CharField(max_length=10, verbose_name='公告日期'),
        ),
        migrations.AlterField(
            model_name='fundportfolio',
            name='end_date',
            field=models.CharField(max_length=10, verbose_name='截止日期'),
        ),
        migrations.AlterField(
            model_name='fundportfolio',
            name='symbol',
            field=models.CharField(max_length=15, verbose_name='股票代码'),
        ),
        migrations.AlterField(
            model_name='fundportfolio',
            name='ts_code',
            field=models.CharField(max_length=15, verbose_name='TS基金代码'),
        ),
    ]
