# Generated by Django 2.2 on 2020-03-26 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_auto_20200321_0841'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='income',
            unique_together={('ts_code', 'end_date')},
        ),
    ]
