# Generated by Django 2.2 on 2020-03-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_auto_20200326_1234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='express',
            unique_together={('ts_code', 'end_date')},
        ),
    ]
