# Generated by Django 2.2 on 2020-04-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_auto_20200326_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdertrade',
            name='holder_name',
            field=models.CharField(max_length=500, verbose_name='股东名称'),
        ),
    ]
