# Generated by Django 2.2 on 2020-02-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbond', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cbondlist',
            old_name='full_name',
            new_name='bond_full_name',
        ),
        migrations.RenameField(
            model_name='cbondlist',
            old_name='short_name',
            new_name='bond_short_name',
        ),
        migrations.RenameField(
            model_name='cbondlist',
            old_name='stock_code',
            new_name='stk_code',
        ),
        migrations.RenameField(
            model_name='cbondlist',
            old_name='stock_name',
            new_name='stk_short_name',
        ),
        migrations.RenameField(
            model_name='cbondlist',
            old_name='code',
            new_name='ts_code',
        ),
    ]
