# Generated by Django 2.2 on 2020-03-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbond', '0002_auto_20200229_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbondlist',
            name='issue_size',
            field=models.FloatField(verbose_name='发行总额（亿元）'),
        ),
        migrations.AlterField(
            model_name='cbondlist',
            name='remain_size',
            field=models.FloatField(verbose_name='债券余额（亿元）'),
        ),
    ]
