# Generated by Django 2.2 on 2020-03-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbond', '0003_auto_20200302_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbondlist',
            name='conv_end_date',
            field=models.CharField(max_length=10, verbose_name='转股截止日'),
        ),
        migrations.AlterField(
            model_name='cbondlist',
            name='conv_start_date',
            field=models.CharField(max_length=10, verbose_name='转股起始日'),
        ),
        migrations.AlterField(
            model_name='cbondlist',
            name='delist_date',
            field=models.CharField(max_length=10, verbose_name='摘牌日'),
        ),
        migrations.AlterField(
            model_name='cbondlist',
            name='list_date',
            field=models.CharField(max_length=10, verbose_name='上市日期'),
        ),
        migrations.AlterField(
            model_name='cbondlist',
            name='maturity_date',
            field=models.CharField(max_length=10, verbose_name='到期日期'),
        ),
        migrations.AlterField(
            model_name='cbondlist',
            name='value_date',
            field=models.CharField(max_length=10, verbose_name='起息日期'),
        ),
    ]
