# Generated by Django 2.2 on 2020-03-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbond', '0004_auto_20200320_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbondlist',
            name='call_clause',
            field=models.CharField(max_length=5000, verbose_name='回售条款'),
        ),
        migrations.AlterField(
            model_name='cbondlist',
            name='conv_clause',
            field=models.CharField(max_length=5000, verbose_name='转股条款'),
        ),
        migrations.AlterField(
            model_name='cbondlist',
            name='maturity_put_price',
            field=models.CharField(max_length=500, verbose_name='到期赎回价格(含税)'),
        ),
        migrations.AlterField(
            model_name='cbondlist',
            name='put_clause',
            field=models.CharField(max_length=5000, verbose_name='赎回条款'),
        ),
        migrations.AlterField(
            model_name='cbondlist',
            name='rate_clause',
            field=models.CharField(max_length=5000, verbose_name='利率说明'),
        ),
        migrations.AlterField(
            model_name='cbondlist',
            name='rate_type',
            field=models.CharField(max_length=5000, verbose_name='利率类型'),
        ),
        migrations.AlterField(
            model_name='cbondlist',
            name='reset_clause',
            field=models.CharField(max_length=5000, verbose_name='特别向下修正条款'),
        ),
    ]
